---
title: "Finance Quantitative"
subtitle: "Modèle de Black-Litterman"
author: Le groupe de travail
date: "Version: `r format(Sys.Date(), '%d %b %Y')`"
output:
  pdf_document:
    keep_tex: false
    fig_caption: yes
    latex_engine: pdflatex
    extra_dependencies: ["float"]
geometry: margin=1in

header-includes:
  - \usepackage[utf8]{inputenc}
  - \usepackage{float}
  - \floatplacement{figure}{H}
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = FALSE)
knitr::opts_chunk$set(fig.pos = "h", out.extra = "")
```

```{r load-libraries, include=TRUE, echo=FALSE, message=FALSE, warning=FALSE}
library(xts)
library(hornpa)
library(lubridate)
library(xtable)
library(quantmod)
library(PerformanceAnalytics)
library(TTR)
library(lubridate)
library(roll)
library(Hmisc)
library(nFactors)
library(kableExtra)
library(broom)

```

* Effectuer une lecture attentive de l'article de He et Litterman.

* A partir de la note de cours, reproduire les autres exemples de l'article,
comparer les résultats avec ceux obtenus avec le package BLCOP.

* Comparer avec une allocation MV classique.

